#APP
server.port=${PORT:8080}
spring.application.name=portfolio-tracker

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_db
spring.datasource.username=root
spring.datasource.password=root1234

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

#DevTools
spring.devtools.add-properties=false
spring.main.allow-bean-definition-overriding=true

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#JWT
jwt.secret=mySecretKeyForPortfolioTrackerApplicationThatIsLongEnough